apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.EngineConfig.RoleName}}
  namespace: {{.EngineConfig.Namespace}}
  labels:
    from: {{.EngineConfig.RoleName}}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/status
  - pods/log
  - services
  - services/status
  - endpoints
  - endpoints/status
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete