apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.EngineConfig.RoleBindingName}}
  namespace: {{.EngineConfig.Namespace}}
  labels:
    from: {{.EngineConfig.RoleName}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{.EngineConfig.RoleName}}
subjects:
- kind: ServiceAccount
  name: {{.EngineConfig.ServiceAccountName}}
  namespace: {{.EngineConfig.Namespace}}